FROM python:3.14@sha256:61346539f7b26521a230e72c11da5ebd872924745074b19736e7d65ba748c366

# Set the working directory in the container
WORKDIR /build

# Copy the requirements file to the container
COPY requirements.txt .
COPY requirements-test.txt .

# Install the Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -r requirements-test.txt


